workspace:
  base: /go
  path: src/github.com/myth/ulv-auth

pipeline:
  test:
    image: lushdigital/docker-golang-dep
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - go get -u golang.org/x/tools/cmd/cover
      - cd /go/src/github.com/myth/ulv-auth
      - /go/bin/dep ensure
      - go test -cover $(go list ./... | grep -v /vendor/)

  build:
    image: lushdigital/docker-golang-dep
    commands:
      - /go/bin/dep ensure
      - go build
    when:
      event: [ push, tag ]

  deploy:
    image: plugins/ssh
    when:
      branch: master
      event: push
    host: ace.ulv.io
    port: 22
    username: root
    secrets: [ ssh_key ]
    script:
      - echo systemctl status ulv-auth
      - echo Change this to restart later

